/* 
 * Employex
 *
 * This is a sample API that allows to manage Employex system, which serves for users seeking to apply for job offers. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ricardorzan@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Employex.Client.SwaggerDateConverter;

namespace Employex.Model
{
    /// <summary>
    /// Different&#x27;s categories of job
    /// </summary>
    /// <value>Different&#x27;s categories of job</value>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum JobCategory
    {
        /// <summary>
        /// Enum CARPINTERO for value: CARPINTERO
        /// </summary>
        [EnumMember(Value = "CARPINTERO")]
        CARPINTERO = 1,
        /// <summary>
        /// Enum CERRAJERO for value: CERRAJERO
        /// </summary>
        [EnumMember(Value = "CERRAJERO")]
        CERRAJERO = 2,
        /// <summary>
        /// Enum MECANICO for value: MECANICO
        /// </summary>
        [EnumMember(Value = "MECANICO")]
        MECANICO = 3,
        /// <summary>
        /// Enum OBRERO for value: OBRERO
        /// </summary>
        [EnumMember(Value = "OBRERO")]
        OBRERO = 4,
        /// <summary>
        /// Enum FONTANERO for value: FONTANERO
        /// </summary>
        [EnumMember(Value = "FONTANERO")]
        FONTANERO = 5,
        /// <summary>
        /// Enum SOLDADOR for value: SOLDADOR
        /// </summary>
        [EnumMember(Value = "SOLDADOR")]
        SOLDADOR = 6,
        /// <summary>
        /// Enum ARTISTA for value: ARTISTA
        /// </summary>
        [EnumMember(Value = "ARTISTA")]
        ARTISTA = 7,
        /// <summary>
        /// Enum SASTRE for value: SASTRE
        /// </summary>
        [EnumMember(Value = "SASTRE")]
        SASTRE = 8,
        /// <summary>
        /// Enum AGRIGULTOR for value: AGRIGULTOR
        /// </summary>
        [EnumMember(Value = "AGRIGULTOR")]
        AGRIGULTOR = 9,
        /// <summary>
        /// Enum COCINERO for value: COCINERO
        /// </summary>
        [EnumMember(Value = "COCINERO")]
        COCINERO = 10,
        /// <summary>
        /// Enum REPARTIDOR for value: REPARTIDOR
        /// </summary>
        [EnumMember(Value = "REPARTIDOR")]
        REPARTIDOR = 11,
        /// <summary>
        /// Enum SEGURIDAD for value: SEGURIDAD
        /// </summary>
        [EnumMember(Value = "SEGURIDAD")]
        SEGURIDAD = 12,
        /// <summary>
        /// Enum ESTILISTA for value: ESTILISTA
        /// </summary>
        [EnumMember(Value = "ESTILISTA")]
        ESTILISTA = 13,
        /// <summary>
        /// Enum EXTERMINADOR for value: EXTERMINADOR
        /// </summary>
        [EnumMember(Value = "EXTERMINADOR")]
        EXTERMINADOR = 14,
        /// <summary>
        /// Enum CAMARERO for value: CAMARERO
        /// </summary>
        [EnumMember(Value = "CAMARERO")]
        CAMARERO = 15,
        /// <summary>
        /// Enum CONDUCTOR for value: CONDUCTOR
        /// </summary>
        [EnumMember(Value = "CONDUCTOR")]
        CONDUCTOR = 16,
        /// <summary>
        /// Enum ELECTRICISTA for value: ELECTRICISTA
        /// </summary>
        [EnumMember(Value = "ELECTRICISTA")]
        ELECTRICISTA = 17,
        /// <summary>
        /// Enum FOTOGRAFO for value: FOTOGRAFO
        /// </summary>
        [EnumMember(Value = "FOTOGRAFO")]
        FOTOGRAFO = 18,
        /// <summary>
        /// Enum CASERO for value: CASERO
        /// </summary>
        [EnumMember(Value = "CASERO")]
        CASERO = 19,
        /// <summary>
        /// Enum JARDINERO for value: JARDINERO
        /// </summary>
        [EnumMember(Value = "JARDINERO")]
        JARDINERO = 20,
        /// <summary>
        /// Enum VENDEDOR for value: VENDEDOR
        /// </summary>
        [EnumMember(Value = "VENDEDOR")]
        VENDEDOR = 21,
        /// <summary>
        /// Enum DENTISTA for value: DENTISTA
        /// </summary>
        [EnumMember(Value = "DENTISTA")]
        DENTISTA = 22,
        /// <summary>
        /// Enum ENFERMERO for value: ENFERMERO
        /// </summary>
        [EnumMember(Value = "ENFERMERO")]
        ENFERMERO = 23,
        /// <summary>
        /// Enum DOCTOR for value: DOCTOR
        /// </summary>
        [EnumMember(Value = "DOCTOR")]
        DOCTOR = 24,
        /// <summary>
        /// Enum EMPRESARIO for value: EMPRESARIO
        /// </summary>
        [EnumMember(Value = "EMPRESARIO")]
        EMPRESARIO = 25,
        /// <summary>
        /// Enum DEPORTISTA for value: DEPORTISTA
        /// </summary>
        [EnumMember(Value = "DEPORTISTA")]
        DEPORTISTA = 26,
        /// <summary>
        /// Enum ADMINISTRADOR for value: ADMINISTRADOR
        /// </summary>
        [EnumMember(Value = "ADMINISTRADOR")]
        ADMINISTRADOR = 27,
        /// <summary>
        /// Enum SECRETARIO for value: SECRETARIO
        /// </summary>
        [EnumMember(Value = "SECRETARIO")]
        SECRETARIO = 28,
        /// <summary>
        /// Enum SOLDADO for value: SOLDADO
        /// </summary>
        [EnumMember(Value = "SOLDADO")]
        SOLDADO = 29,
        /// <summary>
        /// Enum CIENTIFICO for value: CIENTIFICO
        /// </summary>
        [EnumMember(Value = "CIENTIFICO")]
        CIENTIFICO = 30,
        /// <summary>
        /// Enum PROFESOR for value: PROFESOR
        /// </summary>
        [EnumMember(Value = "PROFESOR")]
        PROFESOR = 31,
        /// <summary>
        /// Enum POLICIA for value: POLICIA
        /// </summary>
        [EnumMember(Value = "POLICIA")]
        POLICIA = 32,
        /// <summary>
        /// Enum GERENTE for value: GERENTE
        /// </summary>
        [EnumMember(Value = "GERENTE")]
        GERENTE = 33,
        /// <summary>
        /// Enum BOMBERO for value: BOMBERO
        /// </summary>
        [EnumMember(Value = "BOMBERO")]
        BOMBERO = 34,
        /// <summary>
        /// Enum INGENIERO for value: INGENIERO
        /// </summary>
        [EnumMember(Value = "INGENIERO")]
        INGENIERO = 35,
        /// <summary>
        /// Enum ARQUITECTO for value: ARQUITECTO
        /// </summary>
        [EnumMember(Value = "ARQUITECTO")]
        ARQUITECTO = 36,
        /// <summary>
        /// Enum PERIODISTA for value: PERIODISTA
        /// </summary>
        [EnumMember(Value = "PERIODISTA")]
        PERIODISTA = 37,
        /// <summary>
        /// Enum BIBLIOTECARIO for value: BIBLIOTECARIO
        /// </summary>
        [EnumMember(Value = "BIBLIOTECARIO")]
        BIBLIOTECARIO = 38,
        /// <summary>
        /// Enum ABOGADO for value: ABOGADO
        /// </summary>
        [EnumMember(Value = "ABOGADO")]
        ABOGADO = 39,
        /// <summary>
        /// Enum OTRO for value: OTRO
        /// </summary>
        [EnumMember(Value = "OTRO")]
        OTRO = 40    }
}
