/* 
 * Employex
 *
 * This is a sample API that allows to manage Employex system, which serves for users seeking to apply for job offers. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ricardorzan@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Employex.Client.SwaggerDateConverter;

namespace Employex.Model
{
    /// <summary>
    /// Defines Sector
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum Sector
    {
        /// <summary>
        /// Enum AGRICULTURAPLANTACIONESUOTROSSECTORESRURALES for value: AGRICULTURA, PLANTACIONES, U OTROS SECTORES RURALES
        /// </summary>
        [EnumMember(Value = "AGRICULTURA, PLANTACIONES, U OTROS SECTORES RURALES")]
        AGRICULTURAPLANTACIONESUOTROSSECTORESRURALES = 1,
        /// <summary>
        /// Enum ALIMENTACIONBEBIDASTABACO for value: ALIMENTACION, BEBIDAS, TABACO
        /// </summary>
        [EnumMember(Value = "ALIMENTACION, BEBIDAS, TABACO")]
        ALIMENTACIONBEBIDASTABACO = 2,
        /// <summary>
        /// Enum COMERCIO for value: COMERCIO
        /// </summary>
        [EnumMember(Value = "COMERCIO")]
        COMERCIO = 3,
        /// <summary>
        /// Enum CONSTRUCCION for value: CONSTRUCCION
        /// </summary>
        [EnumMember(Value = "CONSTRUCCION")]
        CONSTRUCCION = 4,
        /// <summary>
        /// Enum EDUCIACION for value: EDUCIACION
        /// </summary>
        [EnumMember(Value = "EDUCIACION")]
        EDUCIACION = 5,
        /// <summary>
        /// Enum FABRICACIONDEMATERIALDETRANSPORTE for value: FABRICACION DE MATERIAL DE TRANSPORTE
        /// </summary>
        [EnumMember(Value = "FABRICACION DE MATERIAL DE TRANSPORTE")]
        FABRICACIONDEMATERIALDETRANSPORTE = 6,
        /// <summary>
        /// Enum FUNCIONPUBLICA for value: FUNCION PUBLICA
        /// </summary>
        [EnumMember(Value = "FUNCION PUBLICA")]
        FUNCIONPUBLICA = 7,
        /// <summary>
        /// Enum HOTELERIARESTAURACINTURISMO for value: HOTELERIA, RESTAURACIÓN, TURISMO
        /// </summary>
        [EnumMember(Value = "HOTELERIA, RESTAURACIÓN, TURISMO")]
        HOTELERIARESTAURACINTURISMO = 8,
        /// <summary>
        /// Enum INDUSTRIASQUIMICAS for value: INDUSTRIAS QUIMICAS
        /// </summary>
        [EnumMember(Value = "INDUSTRIAS QUIMICAS")]
        INDUSTRIASQUIMICAS = 9,
        /// <summary>
        /// Enum INGENIERIAMECANICAYELECTICA for value: INGENIERIA MECANICA Y ELECTICA
        /// </summary>
        [EnumMember(Value = "INGENIERIA MECANICA Y ELECTICA")]
        INGENIERIAMECANICAYELECTICA = 10,
        /// <summary>
        /// Enum MEDIOSDECOMUNICACIONCULTURAGRAFICOS for value: MEDIOS DE COMUNICACION, CULTURA, GRAFICOS
        /// </summary>
        [EnumMember(Value = "MEDIOS DE COMUNICACION, CULTURA, GRAFICOS")]
        MEDIOSDECOMUNICACIONCULTURAGRAFICOS = 11,
        /// <summary>
        /// Enum MINERIA for value: MINERIA
        /// </summary>
        [EnumMember(Value = "MINERIA")]
        MINERIA = 12,
        /// <summary>
        /// Enum PETROLEOYPRODUCCIONDEGASESREFINACIONDEPETROLEO for value: PETROLEO Y PRODUCCION DE GASES, REFINACION DE PETROLEO
        /// </summary>
        [EnumMember(Value = "PETROLEO Y PRODUCCION DE GASES, REFINACION DE PETROLEO")]
        PETROLEOYPRODUCCIONDEGASESREFINACIONDEPETROLEO = 13,
        /// <summary>
        /// Enum PRODUCCIONDEMATERIALESBASICOS for value: PRODUCCION DE MATERIALES BASICOS
        /// </summary>
        [EnumMember(Value = "PRODUCCION DE MATERIALES BASICOS")]
        PRODUCCIONDEMATERIALESBASICOS = 14,
        /// <summary>
        /// Enum SERVICIOSDECORREOYTELECOMUNICACIONES for value: SERVICIOS DE CORREO Y TELECOMUNICACIONES
        /// </summary>
        [EnumMember(Value = "SERVICIOS DE CORREO Y TELECOMUNICACIONES")]
        SERVICIOSDECORREOYTELECOMUNICACIONES = 15,
        /// <summary>
        /// Enum SERVICIOSDESALUD for value: SERVICIOS DE SALUD
        /// </summary>
        [EnumMember(Value = "SERVICIOS DE SALUD")]
        SERVICIOSDESALUD = 16,
        /// <summary>
        /// Enum SERVICIOSFINANCIEROSSERVICIOSPROFESIONALES for value: SERVICIOS FINANCIEROS, SERVICIOS PROFESIONALES
        /// </summary>
        [EnumMember(Value = "SERVICIOS FINANCIEROS, SERVICIOS PROFESIONALES")]
        SERVICIOSFINANCIEROSSERVICIOSPROFESIONALES = 17,
        /// <summary>
        /// Enum SERVICIOSPUBLICOS for value: SERVICIOS PUBLICOS
        /// </summary>
        [EnumMember(Value = "SERVICIOS PUBLICOS")]
        SERVICIOSPUBLICOS = 18,
        /// <summary>
        /// Enum SILVICULTURAMADERACELULOSAPAPEL for value: SILVICULTURA, MADERA, CELULOSA, PAPEL
        /// </summary>
        [EnumMember(Value = "SILVICULTURA, MADERA, CELULOSA, PAPEL")]
        SILVICULTURAMADERACELULOSAPAPEL = 19,
        /// <summary>
        /// Enum TEXTILESVESTIDOCUEROCALZADO for value: TEXTILES, VESTIDO, CUERO, CALZADO
        /// </summary>
        [EnumMember(Value = "TEXTILES, VESTIDO, CUERO, CALZADO")]
        TEXTILESVESTIDOCUEROCALZADO = 20,
        /// <summary>
        /// Enum TRANSPORTE for value: TRANSPORTE
        /// </summary>
        [EnumMember(Value = "TRANSPORTE")]
        TRANSPORTE = 21,
        /// <summary>
        /// Enum TRANSPORTEMARITIMO for value: TRANSPORTE MARITIMO
        /// </summary>
        [EnumMember(Value = "TRANSPORTE MARITIMO")]
        TRANSPORTEMARITIMO = 22    }
}
